apiVersion: v1 # which api to use for deployment
kind: Service # what kind of service/object you want to create
#meta data for name
metadata:
  name: nginx-svc
  namespace: default #

  #Specification to include ports Selector to connect to the deploy
spec:
  ports:
  - nodePort: 30442 
    port: 80
    protocol: TCP
    targetPort: 80

#Lets define the selector and label to connect to nginx deployment
  selector:
    app: nginx #this label connect this service to deployment
    
    # CreatingLoadBalencer
  type: LoadBalancer